Implemented keyboard design and keys
adaapp/testing-dec2021-team3 pull request #18
Opened 2022-01-13 15:42 UTC by flynnn231

![image](https://user-images.githubusercontent.com/90607622/149361505-a49c4729-d219-46fa-9fe9-ae83af7ef0ed.png)

2022-01-13 15:46 UTC, brunogrcsada requested changes
Looks great Ethan! Netlify build issues must be resolved before merging. We also need to look into the positioning of black keys and the 'margin-left' calculation. Great work :)

2022-01-13 15:53 UTC, Jsimpada reviewed
The bubble in the middle doesn't have the letter for the key being pressed?

2022-01-13 15:59 UTC, melissalupu commented on src/App.js
> +         else return <div onMouseDown={() => play({ id: d.toString() })} style={{marginLeft: ((((i-(18 * 4))*2)*30)).toString() + 'px'}} id='black_key'/>
The equation needs to be improved, the black keys are not in the correct position.🙁

2022-01-13 16:01 UTC, elijaholan reviewed
The keys are not in the right position

2022-01-14 09:45 UTC, brunogrcsada approved these changes
Perfect, tests are passing now!

2022-01-14 09:45 UTC, merged